version: '3.4'

services:
  deploydemo:
    image: deploydemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
