version: '3.4'
services:
  deploydemo:
    image: deploydemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VITE_APP_ID: cac
    ports:
      - 80:4173
