version: '3.4'
services:
  deploydemo:
    image: deploydemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VITE_APP_ID: cac
    ports:
      - 80:4173
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1